name: Run Playwright tests
on: [push, workflow_dispatch]
jobs: 
  run-playwright-tests:
    runs-on: ubuntu-latest
    steps: 
    - name: Check out repository code
      uses: actions/checkout@v4   
    - run: npm ci   
    - run: npx playwright install
    - run: npx playwright test --project=firefox